from distutils.core import setup

setup(
    name='arrrbitrage',
    version='1',
    packages=['build.lib.venv.Lib.site-packages.bs4', 'build.lib.venv.Lib.site-packages.bs4.tests',
              'build.lib.venv.Lib.site-packages.bs4.builder', 'build.lib.venv.Lib.site-packages.jwt',
              'build.lib.venv.Lib.site-packages.jwt.contrib', 'build.lib.venv.Lib.site-packages.jwt.contrib.algorithms',
              'build.lib.venv.Lib.site-packages.attr', 'build.lib.venv.Lib.site-packages.ccxt',
              'build.lib.venv.Lib.site-packages.ccxt.base', 'build.lib.venv.Lib.site-packages.ccxt.async',
              'build.lib.venv.Lib.site-packages.ccxt.async.base', 'build.lib.venv.Lib.site-packages.idna',
              'build.lib.venv.Lib.site-packages.pytz', 'build.lib.venv.Lib.site-packages.yarl',
              'build.lib.venv.Lib.site-packages.numpy', 'build.lib.venv.Lib.site-packages.numpy.ma',
              'build.lib.venv.Lib.site-packages.numpy.ma.tests', 'build.lib.venv.Lib.site-packages.numpy.doc',
              'build.lib.venv.Lib.site-packages.numpy.fft', 'build.lib.venv.Lib.site-packages.numpy.fft.tests',
              'build.lib.venv.Lib.site-packages.numpy.lib', 'build.lib.venv.Lib.site-packages.numpy.lib.tests',
              'build.lib.venv.Lib.site-packages.numpy.core', 'build.lib.venv.Lib.site-packages.numpy.core.tests',
              'build.lib.venv.Lib.site-packages.numpy.f2py', 'build.lib.venv.Lib.site-packages.numpy.f2py.tests',
              'build.lib.venv.Lib.site-packages.numpy.tests', 'build.lib.venv.Lib.site-packages.numpy.compat',
              'build.lib.venv.Lib.site-packages.numpy.linalg', 'build.lib.venv.Lib.site-packages.numpy.linalg.tests',
              'build.lib.venv.Lib.site-packages.numpy.random', 'build.lib.venv.Lib.site-packages.numpy.random.tests',
              'build.lib.venv.Lib.site-packages.numpy.testing', 'build.lib.venv.Lib.site-packages.numpy.testing.tests',
              'build.lib.venv.Lib.site-packages.numpy.testing.nose_tools',
              'build.lib.venv.Lib.site-packages.numpy.distutils',
              'build.lib.venv.Lib.site-packages.numpy.distutils.tests',
              'build.lib.venv.Lib.site-packages.numpy.distutils.command',
              'build.lib.venv.Lib.site-packages.numpy.distutils.fcompiler',
              'build.lib.venv.Lib.site-packages.numpy.matrixlib',
              'build.lib.venv.Lib.site-packages.numpy.matrixlib.tests',
              'build.lib.venv.Lib.site-packages.numpy.polynomial',
              'build.lib.venv.Lib.site-packages.numpy.polynomial.tests', 'build.lib.venv.Lib.site-packages.scipy',
              'build.lib.venv.Lib.site-packages.scipy.io', 'build.lib.venv.Lib.site-packages.scipy.io.arff',
              'build.lib.venv.Lib.site-packages.scipy.io.arff.tests', 'build.lib.venv.Lib.site-packages.scipy.io.tests',
              'build.lib.venv.Lib.site-packages.scipy.io.matlab',
              'build.lib.venv.Lib.site-packages.scipy.io.matlab.tests',
              'build.lib.venv.Lib.site-packages.scipy.io.harwell_boeing',
              'build.lib.venv.Lib.site-packages.scipy.io.harwell_boeing.tests',
              'build.lib.venv.Lib.site-packages.scipy.odr', 'build.lib.venv.Lib.site-packages.scipy.odr.tests',
              'build.lib.venv.Lib.site-packages.scipy._lib', 'build.lib.venv.Lib.site-packages.scipy._lib.tests',
              'build.lib.venv.Lib.site-packages.scipy.misc', 'build.lib.venv.Lib.site-packages.scipy.misc.tests',
              'build.lib.venv.Lib.site-packages.scipy.stats', 'build.lib.venv.Lib.site-packages.scipy.stats.tests',
              'build.lib.venv.Lib.site-packages.scipy.linalg', 'build.lib.venv.Lib.site-packages.scipy.linalg.tests',
              'build.lib.venv.Lib.site-packages.scipy.signal', 'build.lib.venv.Lib.site-packages.scipy.signal.tests',
              'build.lib.venv.Lib.site-packages.scipy.sparse', 'build.lib.venv.Lib.site-packages.scipy.sparse.tests',
              'build.lib.venv.Lib.site-packages.scipy.sparse.linalg',
              'build.lib.venv.Lib.site-packages.scipy.sparse.linalg.eigen',
              'build.lib.venv.Lib.site-packages.scipy.sparse.linalg.eigen.arpack',
              'build.lib.venv.Lib.site-packages.scipy.sparse.linalg.eigen.arpack.tests',
              'build.lib.venv.Lib.site-packages.scipy.sparse.linalg.eigen.lobpcg',
              'build.lib.venv.Lib.site-packages.scipy.sparse.linalg.eigen.lobpcg.tests',
              'build.lib.venv.Lib.site-packages.scipy.sparse.linalg.tests',
              'build.lib.venv.Lib.site-packages.scipy.sparse.linalg.dsolve',
              'build.lib.venv.Lib.site-packages.scipy.sparse.linalg.dsolve.tests',
              'build.lib.venv.Lib.site-packages.scipy.sparse.linalg.isolve',
              'build.lib.venv.Lib.site-packages.scipy.sparse.linalg.isolve.tests',
              'build.lib.venv.Lib.site-packages.scipy.sparse.csgraph',
              'build.lib.venv.Lib.site-packages.scipy.sparse.csgraph.tests',
              'build.lib.venv.Lib.site-packages.scipy.cluster', 'build.lib.venv.Lib.site-packages.scipy.cluster.tests',
              'build.lib.venv.Lib.site-packages.scipy.fftpack', 'build.lib.venv.Lib.site-packages.scipy.fftpack.tests',
              'build.lib.venv.Lib.site-packages.scipy.ndimage', 'build.lib.venv.Lib.site-packages.scipy.ndimage.tests',
              'build.lib.venv.Lib.site-packages.scipy.spatial', 'build.lib.venv.Lib.site-packages.scipy.spatial.tests',
              'build.lib.venv.Lib.site-packages.scipy.special', 'build.lib.venv.Lib.site-packages.scipy.special.tests',
              'build.lib.venv.Lib.site-packages.scipy.special._precompute',
              'build.lib.venv.Lib.site-packages.scipy.optimize', 'build.lib.venv.Lib.site-packages.scipy.optimize._lsq',
              'build.lib.venv.Lib.site-packages.scipy.optimize.tests',
              'build.lib.venv.Lib.site-packages.scipy.optimize._trlib',
              'build.lib.venv.Lib.site-packages.scipy.constants',
              'build.lib.venv.Lib.site-packages.scipy.constants.tests',
              'build.lib.venv.Lib.site-packages.scipy.integrate',
              'build.lib.venv.Lib.site-packages.scipy.integrate._ivp',
              'build.lib.venv.Lib.site-packages.scipy.integrate.tests',
              'build.lib.venv.Lib.site-packages.scipy.interpolate',
              'build.lib.venv.Lib.site-packages.scipy.interpolate.tests',
              'build.lib.venv.Lib.site-packages.scipy._build_utils', 'build.lib.venv.Lib.site-packages.aiodns',
              'build.lib.venv.Lib.site-packages.github', 'build.lib.venv.Lib.site-packages.github.tests',
              'build.lib.venv.Lib.site-packages.twilio', 'build.lib.venv.Lib.site-packages.twilio.jwt',
              'build.lib.venv.Lib.site-packages.twilio.jwt.client',
              'build.lib.venv.Lib.site-packages.twilio.jwt.taskrouter',
              'build.lib.venv.Lib.site-packages.twilio.jwt.validation',
              'build.lib.venv.Lib.site-packages.twilio.jwt.access_token',
              'build.lib.venv.Lib.site-packages.twilio.base', 'build.lib.venv.Lib.site-packages.twilio.http',
              'build.lib.venv.Lib.site-packages.twilio.rest', 'build.lib.venv.Lib.site-packages.twilio.rest.api',
              'build.lib.venv.Lib.site-packages.twilio.rest.api.v2010',
              'build.lib.venv.Lib.site-packages.twilio.rest.api.v2010.account',
              'build.lib.venv.Lib.site-packages.twilio.rest.api.v2010.account.sip',
              'build.lib.venv.Lib.site-packages.twilio.rest.api.v2010.account.sip.domain',
              'build.lib.venv.Lib.site-packages.twilio.rest.api.v2010.account.sip.credential_list',
              'build.lib.venv.Lib.site-packages.twilio.rest.api.v2010.account.sip.ip_access_control_list',
              'build.lib.venv.Lib.site-packages.twilio.rest.api.v2010.account.call',
              'build.lib.venv.Lib.site-packages.twilio.rest.api.v2010.account.queue',
              'build.lib.venv.Lib.site-packages.twilio.rest.api.v2010.account.usage',
              'build.lib.venv.Lib.site-packages.twilio.rest.api.v2010.account.usage.record',
              'build.lib.venv.Lib.site-packages.twilio.rest.api.v2010.account.address',
              'build.lib.venv.Lib.site-packages.twilio.rest.api.v2010.account.message',
              'build.lib.venv.Lib.site-packages.twilio.rest.api.v2010.account.recording',
              'build.lib.venv.Lib.site-packages.twilio.rest.api.v2010.account.recording.add_on_result',
              'build.lib.venv.Lib.site-packages.twilio.rest.api.v2010.account.recording.add_on_result.payload',
              'build.lib.venv.Lib.site-packages.twilio.rest.api.v2010.account.conference',
              'build.lib.venv.Lib.site-packages.twilio.rest.api.v2010.account.incoming_phone_number',
              'build.lib.venv.Lib.site-packages.twilio.rest.api.v2010.account.incoming_phone_number.assigned_add_on',
              'build.lib.venv.Lib.site-packages.twilio.rest.api.v2010.account.available_phone_number',
              'build.lib.venv.Lib.site-packages.twilio.rest.fax', 'build.lib.venv.Lib.site-packages.twilio.rest.fax.v1',
              'build.lib.venv.Lib.site-packages.twilio.rest.fax.v1.fax',
              'build.lib.venv.Lib.site-packages.twilio.rest.chat',
              'build.lib.venv.Lib.site-packages.twilio.rest.chat.v1',
              'build.lib.venv.Lib.site-packages.twilio.rest.chat.v1.service',
              'build.lib.venv.Lib.site-packages.twilio.rest.chat.v1.service.user',
              'build.lib.venv.Lib.site-packages.twilio.rest.chat.v1.service.channel',
              'build.lib.venv.Lib.site-packages.twilio.rest.chat.v2',
              'build.lib.venv.Lib.site-packages.twilio.rest.chat.v2.service',
              'build.lib.venv.Lib.site-packages.twilio.rest.chat.v2.service.user',
              'build.lib.venv.Lib.site-packages.twilio.rest.chat.v2.service.channel',
              'build.lib.venv.Lib.site-packages.twilio.rest.sync',
              'build.lib.venv.Lib.site-packages.twilio.rest.sync.v1',
              'build.lib.venv.Lib.site-packages.twilio.rest.sync.v1.service',
              'build.lib.venv.Lib.site-packages.twilio.rest.sync.v1.service.document',
              'build.lib.venv.Lib.site-packages.twilio.rest.sync.v1.service.sync_map',
              'build.lib.venv.Lib.site-packages.twilio.rest.sync.v1.service.sync_list',
              'build.lib.venv.Lib.site-packages.twilio.rest.sync.v1.service.sync_stream',
              'build.lib.venv.Lib.site-packages.twilio.rest.proxy',
              'build.lib.venv.Lib.site-packages.twilio.rest.proxy.v1',
              'build.lib.venv.Lib.site-packages.twilio.rest.proxy.v1.service',
              'build.lib.venv.Lib.site-packages.twilio.rest.proxy.v1.service.session',
              'build.lib.venv.Lib.site-packages.twilio.rest.proxy.v1.service.session.participant',
              'build.lib.venv.Lib.site-packages.twilio.rest.video',
              'build.lib.venv.Lib.site-packages.twilio.rest.video.v1',
              'build.lib.venv.Lib.site-packages.twilio.rest.video.v1.room',
              'build.lib.venv.Lib.site-packages.twilio.rest.video.v1.room.recording',
              'build.lib.venv.Lib.site-packages.twilio.rest.video.v1.room.room_participant',
              'build.lib.venv.Lib.site-packages.twilio.rest.video.v1.recording',
              'build.lib.venv.Lib.site-packages.twilio.rest.video.v1.composition',
              'build.lib.venv.Lib.site-packages.twilio.rest.notify',
              'build.lib.venv.Lib.site-packages.twilio.rest.notify.v1',
              'build.lib.venv.Lib.site-packages.twilio.rest.notify.v1.service',
              'build.lib.venv.Lib.site-packages.twilio.rest.notify.v1.service.user',
              'build.lib.venv.Lib.site-packages.twilio.rest.studio',
              'build.lib.venv.Lib.site-packages.twilio.rest.studio.v1',
              'build.lib.venv.Lib.site-packages.twilio.rest.studio.v1.flow',
              'build.lib.venv.Lib.site-packages.twilio.rest.studio.v1.flow.engagement',
              'build.lib.venv.Lib.site-packages.twilio.rest.lookups',
              'build.lib.venv.Lib.site-packages.twilio.rest.lookups.v1',
              'build.lib.venv.Lib.site-packages.twilio.rest.monitor',
              'build.lib.venv.Lib.site-packages.twilio.rest.monitor.v1',
              'build.lib.venv.Lib.site-packages.twilio.rest.preview',
              'build.lib.venv.Lib.site-packages.twilio.rest.preview.sync',
              'build.lib.venv.Lib.site-packages.twilio.rest.preview.sync.service',
              'build.lib.venv.Lib.site-packages.twilio.rest.preview.sync.service.document',
              'build.lib.venv.Lib.site-packages.twilio.rest.preview.sync.service.sync_map',
              'build.lib.venv.Lib.site-packages.twilio.rest.preview.sync.service.sync_list',
              'build.lib.venv.Lib.site-packages.twilio.rest.preview.proxy',
              'build.lib.venv.Lib.site-packages.twilio.rest.preview.proxy.service',
              'build.lib.venv.Lib.site-packages.twilio.rest.preview.proxy.service.session',
              'build.lib.venv.Lib.site-packages.twilio.rest.preview.proxy.service.session.participant',
              'build.lib.venv.Lib.site-packages.twilio.rest.preview.studio',
              'build.lib.venv.Lib.site-packages.twilio.rest.preview.studio.flow',
              'build.lib.venv.Lib.site-packages.twilio.rest.preview.studio.flow.engagement',
              'build.lib.venv.Lib.site-packages.twilio.rest.preview.wireless',
              'build.lib.venv.Lib.site-packages.twilio.rest.preview.wireless.sim',
              'build.lib.venv.Lib.site-packages.twilio.rest.preview.understand',
              'build.lib.venv.Lib.site-packages.twilio.rest.preview.understand.service',
              'build.lib.venv.Lib.site-packages.twilio.rest.preview.understand.service.intent',
              'build.lib.venv.Lib.site-packages.twilio.rest.preview.understand.service.field_type',
              'build.lib.venv.Lib.site-packages.twilio.rest.preview.marketplace',
              'build.lib.venv.Lib.site-packages.twilio.rest.preview.marketplace.available_add_on',
              'build.lib.venv.Lib.site-packages.twilio.rest.preview.marketplace.installed_add_on',
              'build.lib.venv.Lib.site-packages.twilio.rest.preview.acc_security',
              'build.lib.venv.Lib.site-packages.twilio.rest.preview.acc_security.service',
              'build.lib.venv.Lib.site-packages.twilio.rest.preview.bulk_exports',
              'build.lib.venv.Lib.site-packages.twilio.rest.preview.bulk_exports.export',
              'build.lib.venv.Lib.site-packages.twilio.rest.preview.hosted_numbers',
              'build.lib.venv.Lib.site-packages.twilio.rest.preview.hosted_numbers.authorization_document',
              'build.lib.venv.Lib.site-packages.twilio.rest.preview.deployed_devices',
              'build.lib.venv.Lib.site-packages.twilio.rest.preview.deployed_devices.fleet',
              'build.lib.venv.Lib.site-packages.twilio.rest.pricing',
              'build.lib.venv.Lib.site-packages.twilio.rest.pricing.v1',
              'build.lib.venv.Lib.site-packages.twilio.rest.pricing.v1.voice',
              'build.lib.venv.Lib.site-packages.twilio.rest.pricing.v1.messaging',
              'build.lib.venv.Lib.site-packages.twilio.rest.pricing.v1.phone_number',
              'build.lib.venv.Lib.site-packages.twilio.rest.accounts',
              'build.lib.venv.Lib.site-packages.twilio.rest.accounts.v1',
              'build.lib.venv.Lib.site-packages.twilio.rest.accounts.v1.credential',
              'build.lib.venv.Lib.site-packages.twilio.rest.trunking',
              'build.lib.venv.Lib.site-packages.twilio.rest.trunking.v1',
              'build.lib.venv.Lib.site-packages.twilio.rest.trunking.v1.trunk',
              'build.lib.venv.Lib.site-packages.twilio.rest.wireless',
              'build.lib.venv.Lib.site-packages.twilio.rest.wireless.v1',
              'build.lib.venv.Lib.site-packages.twilio.rest.wireless.v1.sim',
              'build.lib.venv.Lib.site-packages.twilio.rest.messaging',
              'build.lib.venv.Lib.site-packages.twilio.rest.messaging.v1',
              'build.lib.venv.Lib.site-packages.twilio.rest.messaging.v1.service',
              'build.lib.venv.Lib.site-packages.twilio.rest.taskrouter',
              'build.lib.venv.Lib.site-packages.twilio.rest.taskrouter.v1',
              'build.lib.venv.Lib.site-packages.twilio.rest.taskrouter.v1.workspace',
              'build.lib.venv.Lib.site-packages.twilio.rest.taskrouter.v1.workspace.task',
              'build.lib.venv.Lib.site-packages.twilio.rest.taskrouter.v1.workspace.worker',
              'build.lib.venv.Lib.site-packages.twilio.rest.taskrouter.v1.workspace.workflow',
              'build.lib.venv.Lib.site-packages.twilio.rest.taskrouter.v1.workspace.task_queue',
              'build.lib.venv.Lib.site-packages.twilio.rest.ip_messaging',
              'build.lib.venv.Lib.site-packages.twilio.rest.ip_messaging.v1',
              'build.lib.venv.Lib.site-packages.twilio.rest.ip_messaging.v1.service',
              'build.lib.venv.Lib.site-packages.twilio.rest.ip_messaging.v1.service.user',
              'build.lib.venv.Lib.site-packages.twilio.rest.ip_messaging.v1.service.channel',
              'build.lib.venv.Lib.site-packages.twilio.rest.ip_messaging.v2',
              'build.lib.venv.Lib.site-packages.twilio.rest.ip_messaging.v2.service',
              'build.lib.venv.Lib.site-packages.twilio.rest.ip_messaging.v2.service.user',
              'build.lib.venv.Lib.site-packages.twilio.rest.ip_messaging.v2.service.channel',
              'build.lib.venv.Lib.site-packages.twilio.twiml', 'build.lib.venv.Lib.site-packages.aiohttp',
              'build.lib.venv.Lib.site-packages.certifi', 'build.lib.venv.Lib.site-packages.chardet',
              'build.lib.venv.Lib.site-packages.chardet.cli', 'build.lib.venv.Lib.site-packages.pycares',
              'build.lib.venv.Lib.site-packages.urllib3', 'build.lib.venv.Lib.site-packages.urllib3.util',
              'build.lib.venv.Lib.site-packages.urllib3.contrib',
              'build.lib.venv.Lib.site-packages.urllib3.contrib._securetransport',
              'build.lib.venv.Lib.site-packages.urllib3.packages',
              'build.lib.venv.Lib.site-packages.urllib3.packages.backports',
              'build.lib.venv.Lib.site-packages.urllib3.packages.ssl_match_hostname',
              'build.lib.venv.Lib.site-packages.cchardet', 'build.lib.venv.Lib.site-packages.requests',
              'build.lib.venv.Lib.site-packages.multidict', 'build.lib.venv.Lib.site-packages.setuptools',
              'build.lib.venv.Lib.site-packages.setuptools.extern',
              'build.lib.venv.Lib.site-packages.setuptools._vendor',
              'build.lib.venv.Lib.site-packages.setuptools._vendor.packaging',
              'build.lib.venv.Lib.site-packages.setuptools.command', 'build.lib.venv.Lib.site-packages.async_timeout',
              'build.lib.venv.Lib.site-packages.pkg_resources', 'build.lib.venv.Lib.site-packages.pkg_resources.extern',
              'build.lib.venv.Lib.site-packages.pkg_resources._vendor',
              'build.lib.venv.Lib.site-packages.pkg_resources._vendor.packaging'],
    url='',
    license='',
    author='jesse',
    author_email='jessekhora@gmail.com',
    description=''
)
